"""Swagger request/response examples for the Nadree test database.

Secrets are deliberately represented by placeholders because this data is
served from the public OpenAPI document.
"""

TEST_SPOT = {
    "shopId": "00000000-0000-4000-8000-000000000101",
    "spotMasterId": "00000000-0000-4000-8000-000000000101",
    "spotCode": "NR_TEST_20260921-ORG01",
    "unitCode": "NR_TEST_20260921-ORG01",
    "spotName": "Nadree 테스트 최상위 조직",
    "phone": "+62-000-000-000",
    "location": {
        "address": "Test Organization Address",
        "zipCode": "80000",
        "latitude": -8.65,
        "longitude": 115.216,
    },
}

TEST_MODEL_125 = {
    "modelId": "NRTEST-MODEL-125",
    "brand": "Honda",
    "modelName": "Vario 125",
    "cc": 125,
    "vehicleType": "SCOOTER",
    "modelImageKey": "models/test-vario-125.jpg",
}

TEST_MODEL_155 = {
    "modelId": "NRTEST-MODEL-155",
    "brand": "Yamaha",
    "modelName": "NMAX 155",
    "cc": 155,
    "vehicleType": "SCOOTER",
    "modelImageKey": "models/test-nmax-155.jpg",
}

TEST_PRICE = {
    "currency": "USD",
    "rentalDays": 3,
    "dailyFrom": 25,
    "dailyTo": 25,
    "dailyPriceFrom": 25,
    "dailyPriceTo": 25,
    "rentalFrom": 75,
    "rentalTo": 75,
    "pricingTiers": [{
        "priceType": "BASIC",
        "tierType": "BASIC",
        "minCc": 0,
        "maxCc": 125,
        "dailyPriceFrom": 25,
        "dailyPriceTo": 25,
    }],
    "deliveryStart": 0,
    "deliveryReturn": 0,
    "deliveryTotal": 0,
    "deliveryStartFee": 0,
    "deliveryReturnFee": 0,
    "deliveryTotalFee": 0,
    "totalOptions": [75],
    "totalFrom": 75,
    "totalTo": 75,
    "requestedTotal": 75,
    "calculatedTotalFrom": 75,
    "calculatedTotalTo": 75,
    "finalTotal": 75,
}

TEST_DELIVERY = {
    "deliveryRequestType": "START_AND_RETURN",
    "deliveryRegionId": 990000001,
    "pickupLocation": "Kuta Test Area",
    "returnLocation": "Kuta Test Area",
    "startDeliveryFee": 10,
    "returnDeliveryFee": 10,
    "deliveryTotalFee": 20,
}

TEST_RECORD = {
    "recordType": "RESERVATION",
    "reservationId": "NRTEST-RES-APP-001",
    "bookingId": "NRTEST-RES-APP-001",
    "rentalContractId": None,
    "bookedNo": "BONRTEST-RES-APP-001",
    "reservationStatus": "APPROVED",
    "rentalStatus": None,
    "vehicleAssignmentStatus": "PROVISIONAL",
    "shopId": TEST_SPOT["shopId"],
    "spotMasterId": TEST_SPOT["spotMasterId"],
    "modelId": TEST_MODEL_155["modelId"],
    "paymentAvailability": "PAYMENT_REQUIRED",
    "spot": TEST_SPOT,
    "model": TEST_MODEL_155,
    "startDate": "2026-10-09",
    "returnDate": "2026-10-13",
    "actualStartTime": None,
    "actualEndTime": None,
    "deliveryRequestType": "PICKUP",
    "pickupLocation": None,
    "returnLocation": None,
    "delivery": {
        "deliveryRequestType": "PICKUP",
        "deliveryRegionId": None,
        "pickupLocation": None,
        "returnLocation": None,
        "startDeliveryFee": 0,
        "returnDeliveryFee": 0,
        "deliveryTotalFee": 0,
    },
    "price": dict(TEST_PRICE, dailyFrom=35, dailyTo=35, dailyPriceFrom=35,
                  dailyPriceTo=35, rentalFrom=140, rentalTo=140,
                  totalOptions=[140], totalFrom=140, totalTo=140,
                  requestedTotal=140, calculatedTotalFrom=140,
                  calculatedTotalTo=140, finalTotal=140,
                  pricingTiers=[dict(TEST_PRICE["pricingTiers"][0], maxCc=200,
                                    minCc=126, dailyPriceFrom=35, dailyPriceTo=35)]),
    "payment": None,
}


OPENAPI_EXAMPLES = {
    "Login": {
        "email": "nadree.test.admin@example.com",
        "password": "<test-password>",
        "fcmToken": "<real-device-fcm-token>",
    },
    "AdminSignup": {
        "loginId": "nadree.test.newmanager",
        "email": "nadree.test.newmanager@example.com",
        "password": "<test-password>",
        "name": "Nadree 테스트 일반관리자",
        "phone": "+62-000-000-001",
        "representativeEmail": "nadree.test.admin@example.com",
    },
    "Profile": {
        "name": "Nadree 테스트 대표관리자 수정",
        "email": "nadree.test.admin@example.com",
        "phone": "+62-000-000-000",
        "fcmToken": "<real-device-fcm-token>",
    },
    "FcmToken": {"fcmToken": "<real-device-fcm-token>"},
    "SpotCode": {"spotCode": "NR_TEST_20260921-ORG01"},
    "Email": {"email": "nadree.test.manager@example.com"},
    "AdminId": {"adminId": "00000000-0000-4000-8000-000000000202"},
    "Shop": {
        "shopName": "Nadree 테스트 최상위 조직",
        "location": "Test Organization Address",
        "introduction": "Nadree API 테스트 지점",
        "contact": "+62-000-000-000",
        "email": "nadree.test.admin@example.com",
        "deliveryServiceType": "START_AND_RETURN",
    },
    "RequestAction": {
        "email": "nadree.test.newmanager@example.com",
        "action": "APPROVE",
        "spotMasterId": TEST_SPOT["spotMasterId"],
    },
    "SpotCreate": {
        "spot_name": "Nadree 테스트 하위 지점",
        "unit_type": "spot",
        "parent_spot_id": TEST_SPOT["spotMasterId"],
        "phone": "+62-000-000-002",
        "biz_reg_num": "TEST-BIZ-CHILD-001",
        "address": "Kuta Test Area",
        "address_detail": "Test Shop 1",
        "zip_code": "80361",
        "lat": -8.717,
        "lng": 115.169,
        "contract_start": "2026-01-01",
        "contract_end": "2099-12-31",
    },
    "Page": {"page": 1, "pageSize": 20},
    "Calendar": {
        "page": 1,
        "pageSize": 20,
        "spotCode": TEST_SPOT["spotCode"],
        "startDate": "2026-10-10",
        "endDate": "2026-10-13",
        "modelId": "NRTEST-MODEL-125",
    },
    "Operations": {
        "page": 1,
        "pageSize": 20,
        "startDate": "2026-10-01",
        "endDate": "2026-10-31",
        "recordType": "RESERVATION",
    },
    "VehicleNumber": {"vehicleNumber": "DK-TEST-301"},
    "VehicleCreate": {
        "qrToken": "<server-generated-qr-token>",
        "brand": "Honda",
        "vehicleName": "Vario 125",
        "modelId": "NRTEST-MODEL-125",
        "plateNumber": "DK-TEST-305",
        "vehicleImageKey": "vehicles/test-305.jpg",
    },
    "Detach": {"vehicleNumber": "DK-TEST-301", "division": "QR"},
    "PriceChange": {"vehicleNumber": "DK-TEST-301", "priceType": "BASIC", "priceInfo": None},
    "Qr": {"qrCode": "<server-issued-qr-code>"},
    "Repair": {"vehicleNumber": "DK-TEST-302", "date": "2026-10-03", "reason": "정기 점검"},
    "Move": {"vehicleNumber": "DK-TEST-301", "spotCode": TEST_SPOT["spotCode"]},
    "BookingAction": {"bookedNo": "BONRTEST-RES-REQ-001", "action": "APPROVE"},
    "ReservationCancel": {"reservationId": "NRTEST-RES-REQ-001", "reason": "테스트 취소"},
    "RentApprove": {"qrCode": "<server-issued-qr-code>", "bookedNo": "BONRTEST-RES-APP-001"},
    "TierRange": {"minCc": 0, "maxCc": 125},
    "TierCreate": {"minCc": 0, "maxCc": 125, "price": 25, "type": "BASIC", "spotCode": TEST_SPOT["spotCode"]},
    "Delivery": {
        "spotCode": TEST_SPOT["spotCode"],
        "deliveryRegionId": 990000001,
        "isDeliveryEnabled": True,
        "startDeliveryFee": 10,
        "returnDeliveryFee": 10,
        "memo": "Nadree 테스트 배송 지역",
    },
    "DeliveryDelete": {"spotDeliveryRegionId": 990000001},
    "NadriLogin": {"UID": "NRTEST-USER-001", "fcmToken": "<real-device-fcm-token>"},
    "NadriProfile": {"NAME": "Nadree Test Customer", "Age": 30, "GENDER": "M", "NATIONALITY": "KR"},
    "NadriAvailability": {
        "startDate": "2026-10-10", "returnDate": "2026-10-13", "cc": 125, "deliveryRequested": False,
    },
    "NadriRentalRequest": {
        "spotMasterId": TEST_SPOT["spotMasterId"], "modelId": "NRTEST-MODEL-125",
        "startDate": "2026-10-25", "returnDate": "2026-10-28", "totalPrice": 75,
        "currency": "USD", "deliveryRequested": False,
    },
    "NadriPaymentOrder": {"reservationId": "NRTEST-RES-APP-001"},
    "NadriPaymentCapture": {"paymentId": 2},
    "Status": {"status": "success"},
    "Error": {"status": "fail", "errorCode": "RESERVATION_NOT_APPROVED_FOR_PAYMENT"},
    "Admin": {
        "adminId": "00000000-0000-4000-8000-000000000201",
        "name": "Nadree 테스트 대표관리자",
        "email": "nadree.test.admin@example.com",
        "role": "rental_primary_admin",
    },
    "Tokens": {"status": "success", "accessToken": "<nadree-access-token>", "refreshToken": "<nadree-refresh-token>"},
    "CustomerProfile": {
        "uidToken": "NRTEST-USER-001", "name": "Nadree Test Customer", "age": 30,
        "gender": "M", "nationality": "KR",
    },
    "CustomerLocation": TEST_SPOT["location"],
    "CustomerSpot": TEST_SPOT,
    "CustomerModel": TEST_MODEL_125,
    "CustomerPricingTier": TEST_PRICE["pricingTiers"][0],
    "CustomerPrice": TEST_PRICE,
    "CustomerDelivery": TEST_DELIVERY,
    "CustomerRecord": TEST_RECORD,
    "CustomerUser": {
        "uidToken": "NRTEST-USER-001",
        "name": "Nadree Test Customer",
        "age": 30,
        "gender": "M",
        "nationality": "KR",
        "ongoingRequests": [TEST_RECORD],
    },
    "CustomerAvailabilityItem": {
        "shopId": TEST_SPOT["shopId"], "modelId": TEST_MODEL_125["modelId"],
        "spot": TEST_SPOT, "model": TEST_MODEL_125, "price": TEST_PRICE,
    },
    "CustomerAvailability": {
        "status": "success", "items": [{
            "shopId": TEST_SPOT["shopId"], "modelId": TEST_MODEL_125["modelId"],
            "spot": TEST_SPOT, "model": TEST_MODEL_125, "price": TEST_PRICE,
        }],
    },
    "CustomerLogin": {
        "status": "success", "isNewUser": False,
        "accessToken": "<nadree-user-access-token>", "refreshToken": "<nadree-user-refresh-token>",
        "user": dict({
            "uidToken": "NRTEST-USER-001", "name": "Nadree Test Customer", "age": 30,
            "gender": "M", "nationality": "KR",
        }, ongoingRequests=[TEST_RECORD]),
    },
    "CustomerProfileResult": {
        "status": "success", "user": {
            "uidToken": "NRTEST-USER-001", "name": "Nadree Test Customer", "age": 30,
            "gender": "M", "nationality": "KR",
        },
    },
    "CustomerRequest": {
        "status": "success", "reservationId": "<new-reservation-uuid>",
        "bookingId": "<new-reservation-uuid>", "bookedNo": "BO<new-reservation-uuid>",
        "reservationStatus": "REQUESTED", "vehicleAssignmentStatus": "SOFT_HOLD",
        "paymentAvailability": "WAITING_APPROVAL", "paymentStatus": "WAITING_APPROVAL",
        "shopId": TEST_SPOT["shopId"], "spotMasterId": TEST_SPOT["spotMasterId"],
        "modelId": TEST_MODEL_125["modelId"], "totalPrice": 75, "currency": "USD",
        "deliveryRequestType": "PICKUP", "spot": TEST_SPOT, "model": TEST_MODEL_125,
        "price": TEST_PRICE,
    },
    "CustomerPage": {"status": "success", "items": [TEST_RECORD], "page": 1, "pageSize": 20, "totalCount": 1, "hasNext": False},
    "CustomerPayment": {
        "status": "success", "paymentId": 2, "reservationId": "NRTEST-RES-HAND-001",
        "bookingId": "NRTEST-RES-HAND-001", "shopId": TEST_SPOT["shopId"],
        "paymentStatus": "PAID", "paypalOrderId": "NRTEST-ORDER-PAID-001",
        "paypalCaptureId": "NRTEST-CAPTURE-PAID-001", "approvalUrl": None,
        "totalPrice": 200, "serverTotalPrice": 200, "currency": "USD",
        "payment": {"refundStatus": "NONE", "lastWebhookEventType": "PAYMENT.CAPTURE.COMPLETED"},
    },
    "CustomerCancellation": {
        "status": "success", "reservationId": "NRTEST-RES-REQ-001",
        "bookedNo": "BONRTEST-RES-REQ-001", "reservationStatus": "CANCELED", "refundStatus": "NOT_REQUIRED",
    },
    "HierarchyItem": {
        "spot_master_id": TEST_SPOT["spotMasterId"], "unit_code": TEST_SPOT["unitCode"],
        "spot_name": TEST_SPOT["spotName"], "hierarchy_level": "org", "org_name": TEST_SPOT["spotName"],
        "region_name": None, "is_active": True, "manager_name": "Nadree 테스트 대표관리자",
    },
    "Applicant": {"email": "nadree.test.newmanager@example.com", "name": "Nadree 테스트 일반관리자"},
}

OPENAPI_EXAMPLES.update({
    "SignedInAdmin": dict(OPENAPI_EXAMPLES["Admin"], spotMasterId=TEST_SPOT["spotMasterId"]),
    "SignedIn": {
        "status": "success", "accessToken": "<nadree-access-token>", "refreshToken": "<nadree-refresh-token>",
        "admin": dict(OPENAPI_EXAMPLES["Admin"], spotMasterId=TEST_SPOT["spotMasterId"]),
    },
    "ProfileResult": {
        "status": "success", "adminId": "00000000-0000-4000-8000-000000000201",
        "name": "Nadree 테스트 대표관리자", "email": "nadree.test.admin@example.com",
    },
    "SpotResult": {
        "status": "success", "spotMasterId": TEST_SPOT["spotMasterId"],
        "spotName": TEST_SPOT["spotName"], "unitCode": TEST_SPOT["unitCode"], "isDeliverySupported": True,
    },
    "PrimaryResult": {"status": "success", "primaryAdminId": "00000000-0000-4000-8000-000000000202"},
    "Admins": {
        "status": "success", "admin": [OPENAPI_EXAMPLES["Admin"], {
            "adminId": "00000000-0000-4000-8000-000000000202", "name": "Nadree 테스트 일반관리자",
            "email": "nadree.test.manager@example.com", "role": "rental_manager",
        }],
    },
    "ShopResult": {"spotMasterId": TEST_SPOT["spotMasterId"], "deliveryServiceType": "START_AND_RETURN"},
    "HierarchyItem": {
        "spot_master_id": TEST_SPOT["spotMasterId"], "unit_code": TEST_SPOT["unitCode"],
        "spot_name": TEST_SPOT["spotName"], "hierarchy_level": "org", "org_name": TEST_SPOT["spotName"],
        "region_name": None, "is_active": True, "manager_name": "Nadree 테스트 대표관리자",
    },
    "Hierarchy": {"items": [OPENAPI_EXAMPLES["HierarchyItem"]], "total": 1},
    "CreatedSpot": {
        "spot_id": "00000000-0000-4000-8000-000000000102", "unit_code": "NR_TEST_20260921-ORG01-SP01",
        "spot_name": "Nadree 테스트 하위 지점", "hierarchy_level": "spot", "phone": "+62-000-000-002",
        "biz_reg_num": "TEST-BIZ-CHILD-001", "address": "Kuta Test Area", "zip_code": "80361",
        "lat": -8.717, "lng": 115.169, "contract_start": "2026-01-01", "contract_end": "2099-12-31",
        "is_active": True, "inviteCode": "NR_TEST_CHILD_INVITE_20261001",
    },
    "Applicant": {"email": "nadree.test.newmanager@example.com", "name": "Nadree 테스트 일반관리자"},
    "Applicants": {"status": "success", "admins": [OPENAPI_EXAMPLES["Applicant"]]},
    "AdminSignupResult": {
        "status": "success", "adminId": "<created-admin-uuid>", "requestId": "<request-uuid>",
        "spotMasterId": TEST_SPOT["spotMasterId"], "requestStatus": "REQUESTED",
    },
})
